name: CI/CD Pipeline

# Triggers: Run pipeline on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET (ensure the correct .NET version is used)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./src/MyProject/MyProject.csproj

      # Step 4: Build the project
      - name: Build project
        run: dotnet build ./src/MyProject/MyProject.csproj --no-restore --configuration Release

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test ./tests/MyProject.Tests/MyProject.Tests.csproj --no-build --verbosity normal

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build  # Ensure the deploy job only runs after the build job succeeds

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Publish the application
      - name: Publish project
        run: dotnet publish ./src/MyProject/MyProject.csproj --configuration Release --output ./publish

      # Step 3: Deploy to Azure Web App (example)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
